apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mongodb-passwords
  namespace: mongodb
spec:
  length: 32
  digits: 8
  symbols: 0
  secretKeys:
    - mongodb-passwords
    - mongodb-root-password
    - mongodb-replica-set-key

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-auth
  namespace: mongodb
spec:
  refreshPolicy: CreatedOnce
  target:
    name: mongodb-auth
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mongodb-passwords

---

apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mongodb-auth-to-aws
  namespace: mongodb
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - name: aws-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: mongodb-auth
  data:
    - match:
        secretKey: mongodb-passwords
        remoteRef:
          remoteKey: contact-book/mongodb
          property: mongodb-passwords
    - match:
        secretKey: mongodb-root-password
        remoteRef:
          remoteKey: contact-book/mongodb
          property: mongodb-root-password
    - match:
        secretKey: mongodb-replica-set-key
        remoteRef:
          remoteKey: contact-book/mongodb
          property: mongodb-replica-set-key