services:
  nginx:
    image: nginx:1.28.0-alpine
    restart: always #without this, users will lose acces to the app if the container crashes
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/usr/share/nginx/html
    depends_on:
      app:
        condition: service_healthy
    networks:
      - nginx-app

  app:
    build: .
    restart: unless-stopped #always restart the container unless it stopped manually
    container_name: contact-book-app
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin
      - MONGO_DB=${DB_NAME}
    depends_on:
      - mongodb
    networks:
      - app-db
      - nginx-app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5000/health')\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8.0 
    container_name: mongodb
    restart: unless-stopped # if the container stops, it will be restarted unless it was stopped manually
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    expose:
      - "27017"
    networks:
      - app-db
    volumes:
      - db-data:/data/db

networks:
  app-db:
    driver: bridge
  nginx-app:
    driver: bridge

volumes:
  db-data: